version: '3'
services:
  web_stg_passenger_base:
    build:
      context: ../.
      dockerfile: docker/staging_passenger/Dockerfile.base
      args:
        RUBY_VERSION: "2.2"
    image: ufsc/passenger_ufsc-tcc_base:latest
    environment:
      - DOCKERIZED
      - DB_USERNAME
      - DB_PASSWORD
      - DB_HOST_IP
      - DB_PORT
      - DB_DATABASENAME
      - RAILS_ENV

  web_stg_passenger:
    build:
      context: ../.
      dockerfile: docker/staging_passenger/Dockerfile
      args:
        RUBY_VERSION: "2.2"
    image: ufsc/passenger_ufsc-tcc:latest
    ports:
      - 1081:80
      - 1443:443
    environment:
      - DOCKERIZED
      - DB_USERNAME
      - DB_PASSWORD
      - DB_HOST_IP
      - DB_PORT
      - DB_DATABASENAME
      - RAILS_ENV
    extra_hosts:
      - "homologacao-database:192.168.1.6"
# Caso seja um DNS local, para testes, então adicionar host abaixo
      - "homologacao-moodle35.ifes.br:192.168.1.7"
    volumes:
      - assets_stg:/home/app/repo/shared/assets
      - assets_cache_stg:/home/app/repo/tmp/cache/assets
      - bundle_stg:/home/app/repo/shared/bundle
      - config_stg:/home/app/repo/config
      - log_stg:/home/app/repo/shared/log
      - ssl_stg:/etc/ssl/certs_app
      - upload_stg:/home/app/repo/shared/uploads
    depends_on:
      - redis
      - cache
    command: "./docker/init_stg_with_sidekiq.sh"

  redis:
    image: redis:3.0-alpine
    ports:
      - 6379:6379
  cache:
    image: memcached:alpine
    ports:
      - 11211:11211

volumes:
  assets_stg:
    driver: local
  assets_cache_stg:
    driver: local
  bundle_stg:
    driver: local
  config_stg:
    driver: local
  log_stg:
    driver: local
  ssl_stg:
    driver: local
  upload_stg:
    driver: local
