version: '3'
services:
  web_stg:
    build:
      context: ../.
      dockerfile: docker/staging/Dockerfile
      args:
        RUBY_VERSION: "2.2"
    image: ufsc/ufsc-tcc:latest
#    user: "app:app"
    ports:
      - 3002:3000
    environment:
      - DOCKERIZED
      - DB_USERNAME
      - DB_PASSWORD
      - DB_HOST_IP
      - DB_PORT
      - DB_DATABASENAME
      - RAILS_ENV
    volumes:
      - assets_stg:/home/app/repo/shared/assets
      - upload_stg:/home/app/repo/shared/uploads
      - log_stg:/home/app/repo/shared/log
      - bundle_stg:/home/app/repo/shared/bundle
#    links:
#      - mysql
    depends_on:
      - redis
      - cache
    command: "./docker/init_dev_with_sidekiq.sh"

  redis:
    image: redis:3.0-alpine
  cache:
    image: memcached:alpine

volumes:
  bundle_stg:
    driver: local
  upload_stg:
    driver: local
  assets_stg:
    driver: local
  log_stg:
    driver: local
#  db_test:
#    driver: local